language: clojure
lein: lein2
jdk:
- oraclejdk8
install: true
script:
- curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
- chmod a+x lein
- lein test
- bash brevis_utils_deploy.sh
env:
  global:
  - secure: Nc88GgkG6l9jDTSKTZpBoWDPutGzqMFJvKXt5Ji1ZT8/5BEvO0qRF76AnjIhahq6Cv8PFVjJPWEOzQdTvg+5zJM6Uiv+SsVDRx3ccPK1h8L3bHrwfEBNepYyZsmYzjvnQymHgUvIvTop9fKqJdc96cDecuh0nAJKdwoaxK9Dwvaw1zGGVGB/3N/Qi69TeA2C9nqpAd5/zYcvNshBHDZmoeWg2BQTDdv+VaEbgCtLyc21ZheXYXND701WQJV8StSxvjuZjV79+OoJDu4NCA9S9OkHfMW3WxHgrJA+fVwQedUqpdCUDv1Er52YLnkVJjmezYgaF7HO3TJHw2BoDGvX2UjKGwuhyr+rnBw40XspClJAKBor3Ht+TTK0HHnChQAVqlonepLviLed029cNudFl7WirFOj4UQN/lmPikfpdFUhV0AhSN9uoHwU0nnpb2BBN9ae93whjQJI1Fd3s6HRXICdE4zjfTjp+74GSw0Ss/sCUypD5kbtMx0ahalGvRo4yJndoJukX6dPlb7iglhohOMDUsNR/Cer2x/GUTZZtckfi06JM1YV3JGeWmkdlbdfQXC3UQCUG+81MsLpJ3MwKNZ5Cubyj/2RJ6N4b9hl/944WwXvtVG6acbcdt8nbtsGvUmaKfxu1WDBa/2EDMMgicI8aEEhFzgrjN4bRARQ+OU=
  matrix:
    secure: MH06uL6uHeR4XUHEMCeCt3J7RwgxN+groO6xHwTgkeOQ4TnnQH3r9W6RHHh985FWqX1C0lkRVOaj2II7Di73j8LMl+A7T0UiT7qlUulaFOmBCr0v4hk+RH8HdTVRXxXeU51mFFMWyiMhorM/NqUTLdUoPQO33pgwIS1HQwIknsYE+gasjPlV3hpzWE8n7emCntc1FI4evnasPrvfsJ9uTEnXdbjLTZ8U4FVk613IaWzHByxugAkHz7vnfVOz+Da4dxv52S2RvzbvYfIisE8d53QfEObxO2WN1SNjhhwbFBiYwElzTEIEpaK2Z85N1t8wmnPIb7YqHUhPSpsTgi9SmWuQrjPdWDw9mrUmxdADjT9jvgzC63v+ZFo6k618SS4eT5+6mZyjBVRPFTpfoaiIth1EYzMk/5E3940PURM3L8SQp3Au2IVvqZS6CUziRphTcwRnjVN8Lg+5RkIyfyphdI5eb0wT06Jo70/mHBQpJOO4WdT8Edx7pnfqgfHHCuD2Uk20K7vY9vlK9/gwZdfFYkH7jwv3B+aBVJwWRWR/bfzxxq5bHfKFi70tPTj5rYlkL9sgYGJpaI0HAuDSRH/QxT30vX7LrKpQHVW8johc+aLSPpkn79gHIB4mNQpy+f4j9V69IwueAEtT1eUpVCxYLp8vYSMPwJ/k6WIxmuibHY8=
