language: clojure
lein: lein2
jdk:
- oraclejdk8
install: true
script:
- curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
- chmod a+x lein
- lein test
- bash brevis_utils_deploy.sh
env:
  global: 
  matrix:
  - secure: r355y39sgzDG3XHHmhQMTTrBF+NruUDDZKn1zPBs01S0tKlaqYcDh39/OY3YlfQ4bto7zoKlpRkarr+n5W6w7dxcdzMSiiYdMpWA8kKR5tsZvwGfkVjXz3hl5eytlqgs0t/zh2PEKr7TtzCafGtXxnghhDvI2gS+1DJb6HYHvTLeSVJ0EM/XfcLmhq87aPHZS5mgMBywilOMfLYFCuWJSnnwBsX5xbLs7F7uhfLwyFSxwqvUG9prpQAlRaYJaGEE/rj4ln4uYHABve+JlyqnyC2VDRfB19fHkJzTMFziREdyMQqIVPs7JXuzSPhZ6JmP0FgNo4pcQvsP/4veFOnAaGZTH7Q1SDorlIoym7z3TbHrRM2GNWSa9JL3xr7+yabk8UCjlhCR9g/bM0AvpVcsZl/36l5psYLqks71Mh4TJuDeKW2VW+R4vTVt2Tuz65RoVelRkmL5dqODxqGF1daqOuioZVBh5en8S7W5MLdORJkvYm1ixaQGs0KnqSVhoVL2XzjXmN6QGSiqqbfkoA7Fs9mYZkYGFhLhEn720GB0dQR/8X2cpa6SFVmkWlLN0fGFJ99cWXhjoKgEOPQSAGutpS7YlgMhqwhCJDbDPyaj+CgC6QJRBIxYpkVip8mzItQxk94fO6mVqeAgtNWP2Vcuxos1QwksxxvOzyiwnuvUuyw=
  - secure: Nc88GgkG6l9jDTSKTZpBoWDPutGzqMFJvKXt5Ji1ZT8/5BEvO0qRF76AnjIhahq6Cv8PFVjJPWEOzQdTvg+5zJM6Uiv+SsVDRx3ccPK1h8L3bHrwfEBNepYyZsmYzjvnQymHgUvIvTop9fKqJdc96cDecuh0nAJKdwoaxK9Dwvaw1zGGVGB/3N/Qi69TeA2C9nqpAd5/zYcvNshBHDZmoeWg2BQTDdv+VaEbgCtLyc21ZheXYXND701WQJV8StSxvjuZjV79+OoJDu4NCA9S9OkHfMW3WxHgrJA+fVwQedUqpdCUDv1Er52YLnkVJjmezYgaF7HO3TJHw2BoDGvX2UjKGwuhyr+rnBw40XspClJAKBor3Ht+TTK0HHnChQAVqlonepLviLed029cNudFl7WirFOj4UQN/lmPikfpdFUhV0AhSN9uoHwU0nnpb2BBN9ae93whjQJI1Fd3s6HRXICdE4zjfTjp+74GSw0Ss/sCUypD5kbtMx0ahalGvRo4yJndoJukX6dPlb7iglhohOMDUsNR/Cer2x/GUTZZtckfi06JM1YV3JGeWmkdlbdfQXC3UQCUG+81MsLpJ3MwKNZ5Cubyj/2RJ6N4b9hl/944WwXvtVG6acbcdt8nbtsGvUmaKfxu1WDBa/2EDMMgicI8aEEhFzgrjN4bRARQ+OU=
